# Generated by Django 2.0.13 on 2019-08-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_name',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
    ]
