# Generated by Django 2.0.13 on 2019-08-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0002_city_city_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='name',
        ),
        migrations.AddField(
            model_name='pool',
            name='poo_name',
            field=models.CharField(default='DEFAULT VALUE', max_length=30),
        ),
    ]
