# Generated by Django 2.0.13 on 2019-08-06 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0003_auto_20190806_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pool',
            old_name='poo_name',
            new_name='pool_name',
        ),
    ]
