# Generated by Django 2.2.4 on 2019-09-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0003_auto_20190917_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeinterval',
            name='time',
            field=models.IntegerField(choices=[('3시간', 3)], default=0),
        ),
    ]
