# Generated by Django 2.2.4 on 2019-08-24 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0003_auto_20190824_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeinterval',
            name='time_interval',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 24, 23, 22, 22, 999427)),
        ),
    ]
