# Generated by Django 2.2.4 on 2019-09-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0004_auto_20190917_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeinterval',
            name='time',
            field=models.IntegerField(choices=[(3, '3시간'), (7, '7시간')], default=0),
        ),
    ]
