# Generated by Django 2.2.4 on 2019-09-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0005_auto_20190917_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeinterval',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timeinterval',
            name='time_name',
            field=models.CharField(choices=[(3, '3시간'), (7, '7시간')], default='', max_length=10),
        ),
    ]
