# Generated by Django 2.2.4 on 2019-08-24 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0005_auto_20190824_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_timeinterval',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 24, 23, 33, 50, 902023)),
        ),
    ]
