# Generated by Django 2.0.13 on 2019-08-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0005_price_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='week',
            field=models.CharField(choices=[('WEEK', 'Weekdays'), ('WEEKENDS', 'Weekends')], default='WEEK', max_length=10),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='pool',
            name='pool_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
