# Generated by Django 2.2.4 on 2019-09-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0006_auto_20190917_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeinterval',
            name='time_name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
