# Generated by Django 2.2.4 on 2019-08-24 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0006_auto_20190824_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeinterval',
            name='time_interval',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 24, 23, 44, 55, 631049)),
        ),
    ]
