# Generated by Django 2.0.13 on 2019-08-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0006_auto_20190807_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('MON', 'MON'), ('TUE', 'TUE'), ('WED', 'WED'), ('THU', 'THU'), ('FRI', 'FRI'), ('SAT', 'SAT'), ('SUN', 'SUN')], default='MON', max_length=3),
        ),
    ]
