# Generated by Django 2.0.13 on 2019-08-07 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0007_timetable_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swimapp.Pool'),
        ),
    ]
