# Generated by Django 2.2.4 on 2019-09-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0008_auto_20190918_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.IntegerField(choices=[(1, '월요일'), (2, '화요일'), (3, '수요일'), (4, '목요일'), (5, '금요일'), (6, '토요일'), (7, '일요일')], default=1),
        ),
    ]
