# Generated by Django 2.0.13 on 2019-08-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0009_auto_20190807_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
