# Generated by Django 2.2.4 on 2019-09-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0009_auto_20190923_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='week',
            field=models.CharField(choices=[('평일', '평일'), ('주말', '주말')], default='평일', max_length=10),
        ),
    ]
