# Generated by Django 2.2.4 on 2019-09-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0010_auto_20190923_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='week',
            field=models.CharField(choices=[('평일', '평일'), ('주말', '주말')], default='평일', max_length=10),
        ),
    ]
