# Generated by Django 2.2.4 on 2019-09-28 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0011_timetable_week'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Time',
        ),
    ]
