# Generated by Django 2.0.13 on 2019-08-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0012_auto_20190809_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='price_id',
        ),
        migrations.AddField(
            model_name='price',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
