# Generated by Django 2.2.4 on 2019-09-30 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0012_delete_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='registered',
        ),
    ]
