# Generated by Django 2.0.13 on 2019-08-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0013_auto_20190809_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_info', models.DateTimeField()),
            ],
        ),
    ]
