# Generated by Django 2.0.13 on 2019-08-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0014_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_info',
            new_name='user_time',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_city',
            field=models.CharField(default='', max_length=20),
        ),
    ]
