# Generated by Django 2.2.4 on 2019-10-05 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0014_timetable_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='price',
        ),
        migrations.AddField(
            model_name='timetable',
            name='price',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='swimapp.Price'),
        ),
    ]
