# Generated by Django 2.2.4 on 2019-08-26 14:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0014_auto_20190826_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swimapp.Pool'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 26, 23, 58, 3, 530290)),
        ),
    ]
