# Generated by Django 2.2.4 on 2019-10-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0015_auto_20191005_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='price',
        ),
        migrations.AddField(
            model_name='timetable',
            name='price',
            field=models.ManyToManyField(to='swimapp.Price'),
        ),
    ]
