# Generated by Django 2.2.4 on 2019-08-28 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0015_auto_20190826_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 29, 1, 12, 5, 540230)),
        ),
    ]
