# Generated by Django 2.2.4 on 2019-10-05 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0016_auto_20191005_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='price',
            new_name='real_price',
        ),
    ]
