# Generated by Django 2.2.4 on 2019-10-05 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0017_auto_20191005_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='real_price',
            new_name='price',
        ),
    ]
