# Generated by Django 2.2.4 on 2019-10-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0018_auto_20191005_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
