# Generated by Django 2.2.4 on 2019-10-09 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0019_pool_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='week',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='week',
        ),
    ]
