# Generated by Django 2.2.4 on 2019-08-30 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0020_auto_20190830_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 30, 18, 0, 35, 224459)),
        ),
    ]
