# Generated by Django 2.2.4 on 2019-10-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0020_auto_20191010_0509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='price',
        ),
        migrations.AddField(
            model_name='timetable',
            name='price',
            field=models.IntegerField(default=3500),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
