# Generated by Django 2.2.4 on 2019-11-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0022_auto_20191109_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='price',
            field=models.TextField(null=True),
        ),
    ]
