# Generated by Django 2.2.4 on 2019-08-30 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0022_auto_20190830_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 31, 2, 22, 41, 106383)),
        ),
    ]
