# Generated by Django 2.2.4 on 2019-11-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0023_auto_20191109_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='info',
            field=models.TextField(null=True),
        ),
    ]
