# Generated by Django 2.2.4 on 2019-09-11 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0024_auto_20190911_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 11, 9, 2, 46, 277915)),
        ),
    ]
