# Generated by Django 2.2.4 on 2019-11-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0024_pool_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='homepage',
            field=models.CharField(default='', max_length=30),
        ),
    ]
