# Generated by Django 2.2.4 on 2019-12-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0025_pool_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
