# Generated by Django 2.2.4 on 2019-09-11 00:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0025_auto_20190911_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 11, 9, 5, 8, 69622)),
        ),
    ]
