# Generated by Django 2.2.4 on 2019-09-15 00:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0026_auto_20190911_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist_name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='pool',
            name='city',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 9, 55, 25, 551202)),
        ),
        migrations.AddField(
            model_name='pool',
            name='dist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='swimapp.District'),
        ),
    ]
