# Generated by Django 2.2.4 on 2019-09-15 01:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0027_auto_20190915_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 10, 4, 43, 934075)),
        ),
    ]
