# Generated by Django 2.2.4 on 2019-09-15 01:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0028_auto_20190915_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeinterval',
            name='hour',
            field=models.IntegerField(default='', max_length='2'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 10, 7, 5, 884970)),
        ),
    ]
