# Generated by Django 2.2.4 on 2019-09-15 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0029_auto_20190915_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeinterval',
            old_name='hour',
            new_name='times',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 16, 7, 16, 56, 571582)),
        ),
    ]
