# Generated by Django 2.2.4 on 2019-09-15 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0030_auto_20190916_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeinterval',
            name='times',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 16, 7, 21, 52, 205710)),
        ),
    ]
