# Generated by Django 2.2.4 on 2019-09-15 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0031_auto_20190916_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 16, 7, 27, 20, 710202)),
        ),
    ]
