# Generated by Django 2.2.4 on 2019-09-15 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0032_auto_20190916_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 16, 7, 28, 12, 811232)),
        ),
    ]
