# Generated by Django 2.2.4 on 2019-09-15 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0033_auto_20190916_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeinterval',
            name='times',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 16, 7, 41, 18, 602800)),
        ),
    ]
