# Generated by Django 2.2.4 on 2019-09-15 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0035_auto_20190916_0741'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userinfo',
        ),
    ]
