# Generated by Django 2.2.4 on 2019-09-15 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0037_timeinterval_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='swimapp.City'),
        ),
    ]
