# Generated by Django 2.2.4 on 2019-09-15 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0038_district_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='dist',
        ),
        migrations.AddField(
            model_name='pool',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='swimapp.City'),
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
