# Generated by Django 2.2.4 on 2019-09-15 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0041_timeinterval_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeinterval',
            old_name='hours',
            new_name='times',
        ),
    ]
