# Generated by Django 2.2.4 on 2019-09-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0044_timeinterval_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeinterval',
            name='times',
        ),
        migrations.AddField(
            model_name='timeinterval',
            name='time_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
