# Generated by Django 2.2.4 on 2019-09-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0045_auto_20190916_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeinterval',
            name='time_name',
        ),
        migrations.AddField(
            model_name='timeinterval',
            name='times',
            field=models.IntegerField(default=''),
        ),
    ]
