# Generated by Django 2.2.4 on 2019-09-15 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0046_auto_20190916_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeinterval',
            name='times',
        ),
    ]
