# Generated by Django 2.2.4 on 2019-09-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0048_timeinterval_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeinterval',
            name='times',
            field=models.IntegerField(),
        ),
    ]
