# Generated by Django 2.2.4 on 2019-09-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0051_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='time',
        ),
        migrations.AddField(
            model_name='time',
            name='city_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
