# Generated by Django 2.2.4 on 2019-09-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0052_auto_20190917_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='city_name',
        ),
        migrations.AddField(
            model_name='time',
            name='time',
            field=models.IntegerField(default='0'),
        ),
    ]
