# Generated by Django 2.2.4 on 2019-09-17 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimapp', '0053_auto_20190917_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
